# Generated by Django 5.2.6 on 2025-09-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("ref", models.CharField(blank=True, max_length=155, null=True)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "deposit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
                ),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("apellido", models.CharField(blank=True, max_length=100, null=True)),
                ("cumpleanos", models.DateField(blank=True, null=True)),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("masculino", "masculino"), ("femenino", "femenino")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("ciudad", models.CharField(blank=True, max_length=255, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "numero_de_telefono",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "bonificaciones",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("banned", "banned")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "positions_mine",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("col_deposit", models.CharField(default="0", max_length=25)),
                (
                    "user_status",
                    models.CharField(default="Not activated", max_length=25),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("normal", "normal"),
                            ("verif", "verif"),
                            ("verif2", "verif2"),
                            ("supp", "supp"),
                            ("meet", "meet"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "stage_balance",
                    models.DecimalField(decimal_places=2, default=120.0, max_digits=19),
                ),
                (
                    "verification_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "chicken_trap_coefficient",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
    ]
