# Generated by Django 5.2.6 on 2025-09-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=50)),
                ("src", models.CharField(blank=True, max_length=255)),
                ("label", models.CharField(max_length=100)),
                ("numero_de_cuenta", models.CharField(blank=True, max_length=100)),
                ("nombre", models.CharField(blank=True, max_length=100)),
                ("banco", models.CharField(blank=True, max_length=100)),
                ("ci", models.CharField(blank=True, max_length=50)),
                ("cryptoId", models.CharField(blank=True, max_length=50)),
                ("cuit", models.CharField(blank=True, max_length=50)),
                ("cbu", models.CharField(blank=True, max_length=50)),
                ("nro", models.CharField(blank=True, max_length=50)),
                ("sinpe", models.CharField(blank=True, max_length=50)),
                ("bac", models.CharField(blank=True, max_length=50)),
                ("cta", models.CharField(blank=True, max_length=50)),
                ("cedula", models.CharField(blank=True, max_length=50)),
                ("IBAN", models.CharField(blank=True, max_length=50)),
                ("Identificacion", models.CharField(blank=True, max_length=50)),
                ("Rut", models.CharField(blank=True, max_length=50)),
                ("qr", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, max_length=20)),
                ("is_universal", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CountryPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="api.country",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countries",
                        to="api.paymentmethod",
                    ),
                ),
            ],
        ),
    ]
