# Generated by Django 5.2.6 on 2025-09-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_paymentmethod_countrypaymentmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="IBAN",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="Identificacion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="Rut",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alt",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="bac",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="banco",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="cbu",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="cedula",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="ci",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="cryptoId",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="cta",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="cuit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="nombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="nro",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="numero_de_cuenta",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="qr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="sinpe",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="src",
            field=models.ImageField(
                blank=True, null=True, upload_to="payment_methods/"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
