# Generated by Django 5.2.6 on 2025-09-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_paymentmethod_iban_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("transacciones_data", models.DateTimeField()),
                (
                    "transacciones_monto",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("estado", models.CharField(default="esperando", max_length=20)),
                (
                    "transaccion_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "metodo_de_pago",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("stage_processed", models.BooleanField(default=False)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
