# Generated by Django 5.2.6 on 2025-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialPagos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("transacciones_data", models.DateTimeField()),
                (
                    "transacciones_monto",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, default="esperando", max_length=20, null=True
                    ),
                ),
                (
                    "transaccion_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "metodo_de_pago",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cuenta_corriente",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "numero_de_cuenta",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "tipo_de_documento",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "numero_documento",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("banco", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
