# Generated by Django 5.2.6 on 2025-09-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_userprofile_django_user_alter_userprofile_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_bonus_used",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario ya utilizó su primer bono",
            ),
        ),
    ]
