# Generated by Django 5.2.6 on 2025-10-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_userprofile_first_bonus_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="chat_id",
            field=models.CharField(
                blank=True, help_text="ID чата Telegram", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="file_name",
            field=models.CharField(
                blank=True, help_text="Имя файла чека", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="message_id",
            field=models.CharField(
                blank=True,
                help_text="ID сообщения в Telegram",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Заметки по платежу", null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, help_text="Когда был обработан", null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="processed_by",
            field=models.CharField(
                blank=True, help_text="Кто обработал платеж", max_length=255, null=True
            ),
        ),
    ]
