# Generated by Django 5.2.6 on 2025-10-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_transaction_chat_id_transaction_file_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                help_text="Token para verificación de email",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el email del usuario está verificado",
            ),
        ),
    ]
