# Generated by Django 5.2.6 on 2025-11-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_userprofile_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="order_id",
            field=models.CharField(
                blank=True,
                help_text="ID заказа от платежной системы",
                max_length=255,
                null=True,
            ),
        ),
    ]
